SELECT C1.NAME NAME_X, C2.NAME NAME_Y, COUNT(C1.CART_ID) '장바구니 수'
FROM
    ( SELECT DISTINCT CART_ID, NAME FROM CART_PRODUCTS ) C1,
    ( SELECT DISTINCT CART_ID, NAME FROM CART_PRODUCTS ) C2
WHERE C1.CART_ID = C2.CART_ID AND C1.NAME != C2.NAME
GROUP BY C1.NAME, C2.NAME
ORDER BY C1.NAME, C2.NAME;